name: 'Early Access POC Action'
description: 'Creates a process around to enable early-access programs for trials'
inputs:
  github-token:  
    description: 'Token to use'
    required: true
  opsRepoId:
    description: '[Trial Repo] Repo ID for Ops repo to open issues on'
  approvedUsers:
    description: '[Trial Repo] Comma separated list of users that can approve'
  ops:
    description: Does this run in ops repo or trial repo? True | False
    default: false
  pocProjectID:
    descrption: '[Ops Repo] Trial POC Project ID'
  inProgressColumnID:
    description: '[Ops Repo] Repo ID for Ops repo to open issues on'
  opsLabelID:
    description: [Trial Repo] ID for label to add to the created Ops Issue
runs:
  using: 'node12'
  main: 'index.js'